# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git clone https://G14rb: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@github.com/G14rb/streamlit_skf.git
      git remote add origin https://github.com/G14rb/dbt-streamlit
      git config gc.auto 0
      git config --get-all http.https://github.com/G14rb/dbt-streamlit.extraheader
      git config --get-all http.extraheader
      git config --get-regexp .*extraheader
      git config --get-all http.proxy
      git config http.version HTTP/1.1
      git -c http.extraheader="AUTHORIZATION: basic ***" fetch --force --tags --prune --prune-tags --progress --no-recurse-submodules origin
      
      git checkout --progress --force master

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
